### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by eox** [brian-lui/delete-discord#1]
trying to delete all messages on a server and it fails

Task exception was never retrieved
future: <Task finished coro=<ClientManager.delete_server_coro() done, defined at ddel.py:97> exception=TypeError("close_connection() got an unexpected keyword argument 'force'")>
Traceback (most recent call last):
  File "ddel.py", line 121, in delete_server_coro
    await self.client.logout()
  File "C:\Users\SDESKTOP\Desktop\discord\discord.py-async\discord\client.py", line 426, in logout
    yield from self.close()
  File "C:\Users\SDESKTOP\Desktop\discord\discord.py-async\discord\client.py", line 476, in close
    yield from self.ws.close()
  File "C:\Users\SDESKTOP\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 419, in close
    yield from asyncio.shield(self.close_connection_task)
  File "C:\Users\SDESKTOP\Desktop\discord\discord.py-async\discord\gateway.py", line 517, in close_connection
    yield from super().close_connection(force=force)
TypeError: close_connection() got an unexpected keyword argument 'force'

Just type in the number and press enter
3
Getting server list from Discord, please be patient...
Traceback (most recent call last):
  File "C:\Users\SDESKTOP\Desktop\delete_discord.py", line 256, in <module>
    dog.menu_loop()
  File "C:\Users\SDESKTOP\Desktop\delete_discord.py", line 246, in menu_loop
    func()
  File "C:\Users\SDESKTOP\Desktop\delete_discord.py", line 176, in print_servers
    self.run_coroutine(self.print_servers_coro)
  File "C:\Users\SDESKTOP\Desktop\delete_discord.py", line 172, in run_coroutine
    self.client.run(self.email, self.password)
  File "C:\Users\SDESKTOP\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 575, in run
    return task.result()
  File "C:\Users\SDESKTOP\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 495, in _silence_gathered
    fut.result()
  File "C:\Users\SDESKTOP\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 482, in start
    await self.login(*args, bot=bot)
TypeError: login() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

**Comment by brian-lui** [comment]
Not sure why this happens!

**Comment by tomland123** [comment]
Hi Eox, Discord updated their API to only take a token instead of a password and email.

You can check out the updated version here: https://github.com/tomland123/delete_discord/
